-- Supabase SQL Schema for ESP Smart Control
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard)

-- 1. Devices Table
CREATE TABLE IF NOT EXISTS devices (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  state TEXT NOT NULL,
  ip TEXT NOT NULL,
  rssi INTEGER,
  uptime_seconds INTEGER,
  free_heap INTEGER,
  firmware TEXT,
  last_seen BIGINT NOT NULL,
  latency_ms INTEGER
);

-- 2. Telemetry Table
CREATE TABLE IF NOT EXISTS telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  temperature REAL,
  humidity REAL,
  dht_valid BOOLEAN,
  mq132_raw INTEGER,
  mq132_index REAL,
  mq5_raw INTEGER,
  mq5_index REAL,
  soil_raw INTEGER,
  soil_percent INTEGER,
  soil_state TEXT,
  servo_angle INTEGER,
  pump_active BOOLEAN,
  pump_elapsed_ms INTEGER,
  is_simulated BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_telemetry_created_at ON telemetry(created_at DESC);

-- 3. Commands Queue Table (For Cloud Remote Control from Mobile via Vercel)
CREATE TABLE IF NOT EXISTS commands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  target TEXT NOT NULL, -- 'ESP1' | 'ESP2' | 'SYSTEM'
  action TEXT NOT NULL, -- 'robot_move' | 'deploy_soil' | 'retract_soil' | 'pump_on' | 'pump_off' | 'emergency_stop'
  payload JSONB,
  executed BOOLEAN DEFAULT FALSE,
  executed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_commands_pending ON commands(executed, created_at ASC);

-- 4. Enable Realtime Publications for instant push to phones and controllers
ALTER PUBLICATION supabase_realtime ADD TABLE devices;
ALTER PUBLICATION supabase_realtime ADD TABLE telemetry;
ALTER PUBLICATION supabase_realtime ADD TABLE commands;

-- 5. Open Row Level Security policies for personal IoT project (or configure Auth)
ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE commands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read on devices" ON devices FOR SELECT USING (true);
CREATE POLICY "Allow public write on devices" ON devices FOR ALL USING (true);

CREATE POLICY "Allow public read on telemetry" ON telemetry FOR SELECT USING (true);
CREATE POLICY "Allow public insert on telemetry" ON telemetry FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read on commands" ON commands FOR SELECT USING (true);
CREATE POLICY "Allow public insert on commands" ON commands FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on commands" ON commands FOR UPDATE USING (true);
